[package]
name = "spreadsheet"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
env = "1.0.1"
lalrpop-util = { version = "0.22.1", features = ["lexer", "unicode"] }
logos = "0.14"
# ratatui = "0.29.0"
