[package]
name = "ext"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
csv = "1.3.1"
lalrpop = "0.22.1"
lalrpop-util = "0.22.1"
logos = "0.15.0"
ratatui = "0.29.0"
spreadsheet_core = { path = "../spreadsheet_core" }

[build-dependencies]
lalrpop = "0.22.1"